"""add examination center tables

Revision ID: 39821640569e
Revises: e5f6a1b2c3d4
Create Date: 2026-08-27 12:07:42.167052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39821640569e'
down_revision: Union[str, None] = 'e5f6a1b2c3d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('examination_centers',
    sa.Column('center_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=True),
    sa.Column('key_identifier', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_examination_centers_center_code'), 'examination_centers', ['center_code'], unique=True)
    op.create_index(op.f('ix_examination_centers_id'), 'examination_centers', ['id'], unique=False)
    op.create_index(op.f('ix_examination_centers_key_identifier'), 'examination_centers', ['key_identifier'], unique=False)
    op.create_index(op.f('ix_examination_centers_status'), 'examination_centers', ['status'], unique=False)
    op.create_table('exam_center_associations',
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('center_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['center_id'], ['examination_centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_id', 'center_id')
    )
    op.create_table('center_release_keys',
    sa.Column('examination_center_id', sa.UUID(), nullable=False),
    sa.Column('question_paper_id', sa.UUID(), nullable=False),
    sa.Column('wrapped_key', sa.Text(), nullable=False),
    sa.Column('key_identifier', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['examination_center_id'], ['examination_centers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_paper_id'], ['question_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_center_release_keys_examination_center_id'), 'center_release_keys', ['examination_center_id'], unique=False)
    op.create_index(op.f('ix_center_release_keys_id'), 'center_release_keys', ['id'], unique=False)
    op.create_index(op.f('ix_center_release_keys_key_identifier'), 'center_release_keys', ['key_identifier'], unique=False)
    op.create_index(op.f('ix_center_release_keys_question_paper_id'), 'center_release_keys', ['question_paper_id'], unique=False)
    op.create_table('release_schedules',
    sa.Column('question_paper_id', sa.UUID(), nullable=False),
    sa.Column('release_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_paper_id'], ['question_papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scheduled_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_release_schedules_id'), 'release_schedules', ['id'], unique=False)
    op.create_index(op.f('ix_release_schedules_question_paper_id'), 'release_schedules', ['question_paper_id'], unique=True)
    op.create_index(op.f('ix_release_schedules_status'), 'release_schedules', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_release_schedules_status'), table_name='release_schedules')
    op.drop_index(op.f('ix_release_schedules_question_paper_id'), table_name='release_schedules')
    op.drop_index(op.f('ix_release_schedules_id'), table_name='release_schedules')
    op.drop_table('release_schedules')
    op.drop_index(op.f('ix_center_release_keys_question_paper_id'), table_name='center_release_keys')
    op.drop_index(op.f('ix_center_release_keys_key_identifier'), table_name='center_release_keys')
    op.drop_index(op.f('ix_center_release_keys_id'), table_name='center_release_keys')
    op.drop_index(op.f('ix_center_release_keys_examination_center_id'), table_name='center_release_keys')
    op.drop_table('center_release_keys')
    op.drop_table('exam_center_associations')
    op.drop_index(op.f('ix_examination_centers_status'), table_name='examination_centers')
    op.drop_index(op.f('ix_examination_centers_key_identifier'), table_name='examination_centers')
    op.drop_index(op.f('ix_examination_centers_id'), table_name='examination_centers')
    op.drop_index(op.f('ix_examination_centers_center_code'), table_name='examination_centers')
    op.drop_table('examination_centers')
    # ### end Alembic commands ###
