"""add question_papers table

Revision ID: b2c3d4e5f6a1
Revises: a1b2c3d4e5f6
Create Date: 2026-08-09 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2c3d4e5f6a1'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_papers',
    sa.Column('subject_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('paper_code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('storage_path', sa.String(length=1000), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('approved_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('upload_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'paper_code', 'version', name='uq_paper_code_version_per_subject')
    )
    op.create_index(op.f('ix_question_papers_id'), 'question_papers', ['id'], unique=False)
    op.create_index(op.f('ix_question_papers_paper_code'), 'question_papers', ['paper_code'], unique=False)
    op.create_index(op.f('ix_question_papers_status'), 'question_papers', ['status'], unique=False)
    op.create_index(op.f('ix_question_papers_subject_id'), 'question_papers', ['subject_id'], unique=False)
    op.create_index(op.f('ix_question_papers_uploaded_by'), 'question_papers', ['uploaded_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_papers_uploaded_by'), table_name='question_papers')
    op.drop_index(op.f('ix_question_papers_subject_id'), table_name='question_papers')
    op.drop_index(op.f('ix_question_papers_status'), table_name='question_papers')
    op.drop_index(op.f('ix_question_papers_paper_code'), table_name='question_papers')
    op.drop_index(op.f('ix_question_papers_id'), table_name='question_papers')
    op.drop_table('question_papers')
    # ### end Alembic commands ###
