"""add approval_workflows table

Revision ID: c3d4e5f6a1b2
Revises: b2c3d4e5f6a1
Create Date: 2026-08-09 13:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3d4e5f6a1b2'
down_revision: Union[str, None] = 'b2c3d4e5f6a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approval_workflows',
    sa.Column('question_paper_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('approval_level', sa.String(length=50), nullable=False),
    sa.Column('approver_id', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_paper_id'], ['question_papers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_paper_id', 'approval_level', 'decision', name='uq_pending_approval_level_per_paper')
    )
    op.create_index(op.f('ix_approval_workflows_decision'), 'approval_workflows', ['decision'], unique=False)
    op.create_index(op.f('ix_approval_workflows_id'), 'approval_workflows', ['id'], unique=False)
    op.create_index(op.f('ix_approval_workflows_question_paper_id'), 'approval_workflows', ['question_paper_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_workflows_question_paper_id'), table_name='approval_workflows')
    op.drop_index(op.f('ix_approval_workflows_id'), table_name='approval_workflows')
    op.drop_index(op.f('ix_approval_workflows_decision'), table_name='approval_workflows')
    op.drop_table('approval_workflows')
    # ### end Alembic commands ###
