"""add key_metadata table

Revision ID: d4e5f6a1b2c3
Revises: c3d4e5f6a1b2
Create Date: 2026-08-09 14:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd4e5f6a1b2c3'
down_revision: Union[str, None] = 'c3d4e5f6a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('key_metadata',
    sa.Column('key_identifier', sa.String(length=255), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('key_purpose', sa.String(length=50), nullable=False),
    sa.Column('key_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rotation_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', postgresql.UUID(as_uuid=True), nullable=True),
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_metadata_id'), 'key_metadata', ['id'], unique=False)
    op.create_index(op.f('ix_key_metadata_key_identifier'), 'key_metadata', ['key_identifier'], unique=True)
    op.create_index(op.f('ix_key_metadata_status'), 'key_metadata', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_key_metadata_status'), table_name='key_metadata')
    op.drop_index(op.f('ix_key_metadata_key_identifier'), table_name='key_metadata')
    op.drop_index(op.f('ix_key_metadata_id'), table_name='key_metadata')
    op.drop_table('key_metadata')
    # ### end Alembic commands ###
